# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[(1, '\u5df2\u53d1\u5e03'), (0, '\u5f85\u53d1\u5e03')], max_length=10),
        ),
    ]
