# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_auto_20170831_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='describe',
            field=models.CharField(default=' ', max_length=300, verbose_name='\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=200, verbose_name='\u53d1\u5e03\u4f1a\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.IntegerField(verbose_name='\u6700\u5927\u5bb9\u7eb3\u89c2\u4f17'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Y', '\u5df2\u53d1\u5e03'), ('N', '\u5f85\u53d1\u5e03')], max_length=10, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u6807\u9898'),
        ),
    ]
