# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_auto_20170831_1316'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together=set([]),
        ),
    ]
