# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-01 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_auto_20170831_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('True', '\u5df2\u53d1\u5e03'), ('False', '\u5f85\u53d1\u5e03')], default='False', max_length=10, verbose_name='\u72b6\u6001'),
        ),
    ]
